"""Init empty db

Revision ID: 0461773d6863
Revises:
Create Date: 2024-10-27 13:58:15.472835

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0461773d6863"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "software",
        sa.Column("software_id", sa.Uuid(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("maintainer_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "maintainer_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("software_id"),
    )
    op.create_index(
        op.f("ix_software_display_name"), "software", ["display_name"], unique=True
    )
    op.create_table(
        "release",
        sa.Column("release_id", sa.Uuid(), nullable=False),
        sa.Column("version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("release_date", sa.Date(), nullable=False),
        sa.Column("software_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["software_id"], ["software.software_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("release_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release")
    op.drop_index(op.f("ix_software_display_name"), table_name="software")
    op.drop_table("software")
    # ### end Alembic commands ###
