"""Add software description and code url

Revision ID: 7014deb36db2
Revises: 0461773d6863
Create Date: 2024-10-27 14:39:47.193874

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7014deb36db2"
down_revision: Union[str, None] = "0461773d6863"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "software",
        sa.Column("code_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "software",
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=280), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("software", "description")
    op.drop_column("software", "code_url")
    # ### end Alembic commands ###
